### ISSUE TITLE
반찬 썸네일 이미지 모두 크롤링하기

### ISSUE THREAD

**Issue by kimdaeman14** [FC-Oasis/baeminchan-django#24]
제품 상세페이지 서버 연동시에 썸네일 이미지가 하나만 있는데 크롤링하시면 여러개로는 안나오나요 ?

모바일 앱에서는 몇초마다 이미지가 하나씩 변경되는 식으로 해서 4~5개씩은 있어서요~

**Comment by yeojin-dev** [comment]
@kimdaeman14 현재 크롤링 코드에서는 썸네일 이미지를 하나만 가져옵니다. 어렵지 않을 것 같은데 다른 팀원들과 일정을 어떻게 할지 오늘 논의해보겠습니다. 😊
