### ISSUE TITLE
Product 모델의 related_products 필드 데이터 업데이트

### ISSUE THREAD

**Issue by kimdaeman14** [FC-Oasis/baeminchan-django#25]
제품상세페이지에 
related_products | ​ | ​ | 반찬 가게의 다른 상품들
경우에는 현재 빈배열로 되어있는데 저희가 임의로 다른 리스트를 불러와야될까요? 
아니면 아직 안만들어져있는건가요 ?

**Comment by yeojin-dev** [comment]
@kimdaeman14 이 부분은 금요일까지 업데이트하겠습니다. 💻
